language: go
go:
    - 1.13.x

before_install:
    - go get -t -v ./...

install:
    - go get github.com/Sperax/bdls/

script:
    - go test -v -coverprofile=coverage.txt.tmp -covermode=atomic -timeout 12h -run "(Verify)|(Full20Participants)|(Propose)|(Round)|(Commit)|(Lock)|(Stage)"
    - cat coverage.txt.tmp | grep -v "pb.go" > coverage.txt
    - rm coverage.txt.tmp

after_success:
    - bash <(curl -s https://codecov.io/bash)
